apiVersion: apps/v1
kind: Deployment
metadata:
  name: arzmeta-youtube-dl
  labels:
    app: arzmeta-youtube-dl
  namespace: namespace-arzmeta-youtube-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arzmeta-youtube-dl
  template:
    metadata:
      labels:
        app: arzmeta-youtube-dl
    spec:
      containers:
        - name: arzmeta-youtube-dl
          image: arzmetawebserveracr.azurecr.io/arzmeta-youtube-dl:latest
          ports:
            - containerPort: 8080