apiVersion: v1
kind: Service
metadata:
  name: dev-youtube-dl
  namespace: namespace-workflow-1698897992635
spec:
  type: LoadBalancer
  selector:
    app: dev-youtube-dl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080