apiVersion: v1
kind: Service
metadata:
  name: dev-youtube-dl
  namespace: namespace-workflow-1698806962346
spec:
  type: LoadBalancer
  selector:
    app: dev-youtube-dl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
