apiVersion: v1
kind: Service
metadata:
  name: arzmeta-youtube-dl
  namespace: namespace-arzmeta-youtube-dl
spec:
  type: LoadBalancer
  selector:
    app: arzmeta-youtube-dl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080